name: Deploy shared-ui to Azure Static Web Apps

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Clean previous build artifacts
        run: |
          rm -rf dist/
          rm -rf node_modules/.cache/
          rm -rf .pnpm-store/

      - name: Install dependencies
        run: pnpm install

      - name: Build app
        run: pnpm build

      - name: Copy staticwebapp.config.json to dist
        run: cp staticwebapp.config.json dist/

      - name: List dist contents
        run: ls -l dist

      - name: Upload to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          app_location: .
          output_location: dist
          action: upload
          app_build_command: pnpm build
